### ISSUE TITLE
Add a table of contents to the help page.

### ISSUE THREAD

**Issue by KHarshawat** [department-of-veterans-affairs/caseflow-certification#105]
Each question should have a tag assocaited with it so you can jump to the question you're looking for by clicking on it's link in the table of contents.

**Comment by orischwartz** [comment]
Can auto-generate this by pasting javascript into console if we put unique id's on all h2 tags:

```javascript
$(".cf-app-segment h2").each(function(i) {
    var current = $(this);
    $("#toc").append("<li><a href='#" +
        current.attr("id") + "'>" + 
        current.html() + "</a></li>");
});
```
