### ISSUE TITLE
Port the VBMS is down error page when a user attempts to certify a case

### ISSUE THREAD

**Issue by KHarshawat** [department-of-veterans-affairs/caseflow-certification#109]
https://cloud.githubusercontent.com/assets/354277/12020461/cc98b3c6-ad4a-11e5-8b83-2e1f556b6d01.png

also see https://github.com/department-of-veterans-affairs/caseflow/issues/253

**Comment by orischwartz** [comment]
This is mostly done in #134 but we need to adjust the text to match the screenshot.

**Comment by orischwartz** [comment]
Blocked by #134
