### ISSUE TITLE
wget PhantomJS takes 35 seconds in travis

### ISSUE THREAD

**Issue by orischwartz** [department-of-veterans-affairs/caseflow-certification#113]
via @awong-dev, there are two solutions:

> 1. add the directory you're taring into into the `cache` directories like `vendor/bundler` and write a bash if-statement to not wget if the directory exists. 
> 2. use `npm install` with a very small `package.json` and cache all of `node_modules` and execute phantom via `npm run`.

**Comment by orischwartz** [comment]
Actually it looks like phantomjs get is only taking ~5sec? e.g., [this build](https://travis-ci.org/department-of-veterans-affairs/caseflow-certification/builds/113757438)

**Comment by awong-dev** [comment]
hmm... good catch. Maybe not worth it then.

**Comment by orischwartz** [comment]
We get wildly inconsistent performance from our Travis builds ...e.g., today `libgcj12` took 20+ min. We should look into caching everything we can.

**Comment by shanear** [comment]
@orischwartz so it looks like npm downloads phantom from the same source we do:
(see: https://www.npmjs.com/package/phantomjs2)

also, travis has different caches for different branches, and isn't really going to help performance:
https://docs.travis-ci.com/user/caching/#Things-not-to-cache

I think our best bet is to have our own s3 bucket mirror of phantomJS. What do you think of that idea?

**Comment by awong-dev** [comment]
I will throw out the caveat that we're doing just fine in vets-website with cached node_modules and we use PhantomJS (1.9 not 2, but problem _should_ be roughly the same...).

I also seem to notice that if you cache on master, the cache does seem to get inherited somehow despite what the documentation says.

Maybe try npm first before doing something more esoteric?  It's pretty easy to set up.

**Comment by shanear** [comment]
@awong-dev  1.9.2 would be the best, cause it's automatically installed on Travis, but our PDF viewer breaks in it.

I'll look into npm, maybe it caches the binary?
