### ISSUE TITLE
Add new Caseflow logo! 

### ISSUE THREAD

**Issue by KHarshawat** [department-of-veterans-affairs/caseflow-certification#117]
I almost completely forgot, we gotta definitely add the new Caseflow logo to the app before launch :)

**Comment by shanear** [comment]
:haircut:

**Comment by orischwartz** [comment]
@KHarshawat The current caseflow text "logo" is 64.67x22px. The navbar it goes into is 83px high. 

![navbar](https://cloud.githubusercontent.com/assets/16327036/13579049/6f16e42e-e469-11e5-926d-d038189fe7e5.png)

**Comment by KHarshawat** [comment]
![caseflow-certification-logo_1x](https://cloud.githubusercontent.com/assets/6335546/13607407/01aacb20-e51e-11e5-9fa4-66c62f986a7d.png)
![caseflow-certification-logo_2x](https://cloud.githubusercontent.com/assets/6335546/13607408/01acc358-e51e-11e5-95ff-d4162263a41c.png)
