### ISSUE TITLE
Add a 500 page

### ISSUE THREAD

**Issue by KHarshawat** [department-of-veterans-affairs/caseflow-certification#118]
I'd like to verify what the 500 page (for when VACOLS is down) looks like. I don't have them tracked based on these issues but I'm sure we have them.

https://github.com/department-of-veterans-affairs/appeals-pm/issues/150
https://github.com/department-of-veterans-affairs/caseflow/issues/190

Can someone please add a screenshot of what it looks like. In the off chance we don't have a good looking one, I'd like to design it and fix the copy before launch.

**Comment by orischwartz** [comment]
Use errors layout, red for 500, gray for 404
