### ISSUE TITLE
Differentiate between VACOLS login errors

### ISSUE THREAD

**Issue by KHarshawat** [department-of-veterans-affairs/caseflow-certification#119]
When a user enters a user-name that isn't in the system:

> The username you entered could not be found.

When a user enters a username but the pw doesn't check out:

> The username and password you entered do not match.

**Comment by shanear** [comment]
@KHarshawat surprisingly, because of the mechanism we're using to log in, this might be technically challenging.

additionally, many login systems won't tell you if the username you entered was valid (i think for security reasons).

**Comment by orischwartz** [comment]
Yeah we decided in this situation there was no harm--end users are already SSOI-authenticated and it could increase usability. But agree that this is very low priority given how we're currently authenticating in VACOLS. This falls under nice-to-have.

**Comment by shanear** [comment]
This was deemed to difficult for the gain. Closing.
