### ISSUE TITLE
upcase the RO on user login before storing in session

### ISSUE THREAD

**Issue by paultag** [department-of-veterans-affairs/caseflow-certification#162]

**Comment by orischwartz** [comment]
Our authentication is case-insensitive so a user could log in with lowercase RO.

**Comment by orischwartz** [comment]
Confirmed, we determine access to appeal by doing a [case-sensitive](https://github.com/department-of-veterans-affairs/caseflow-certification/blob/master/app/models/user.rb#L36) comparison
