### ISSUE TITLE
Add unit tests for AppealRepository#sanitize_vbms_id

### ISSUE THREAD

**Issue by orischwartz** [department-of-veterans-affairs/caseflow-certification#185]
Logic is different for `C` and `S` types. /cc @paultag 

https://github.com/department-of-veterans-affairs/caseflow/blob/addcb0cb4bd105f1c46baa0428f97364897913f4/app/models/case.rb#L162-L168

**Comment by orischwartz** [comment]
In order to do this we'd need to move `sanitize_vbms_id` out of `AppealRepository` (so as not to introduce testing dependencies on ConnectVBMS). 

@shanear Any thoughts on where it can go? We could add a `vbms_id_padded` method to `Appeal` but that doesn't feel like the best place.

**Comment by shanear** [comment]
agreed, but i think it might be the best option. The other option is to break all vbms stuff out of AppealRepository, which seems messier.

I'm cool with just adding a `sanitized_vbms_id` method to appeal.
