### ISSUE TITLE
Recreation of Caseflow Reports

### ISSUE THREAD

**Issue by gmorgana-va** [department-of-veterans-affairs/caseflow-certification#211]
Recreation of the original Caseflow reports following the refactoring of the Caseflow codebase (including https://github.com/department-of-veterans-affairs/appeals-pm/issues/85).

**Comment by paultag** [comment]
(Unassigning myself from bugs I've dropped and have expired)

There's an open PR with some of this, just needs to likely be rebased and cleaned up :+1:

**Comment by KHarshawat** [comment]
@cmgiven might be up your alley

**Comment by cmgiven** [comment]
Closing. See #345.
