### ISSUE TITLE
Saved form8 serialization has no concept of object versioning, which can lead to silent conversion bugs 

### ISSUE THREAD

**Issue by orischwartz** [department-of-veterans-affairs/caseflow-certification#214]
1. User accesses form 8
1. Form 8 serialized to session
1. New version of CF deployed, changing the type of a serialized attribute from `String`->`Date`
1. User accesses same case
1. System populates form 8 with `String` instead of `Date`
1. System silently fails to convert date->string, shows blank (`nil`)

Does `ActiveModel::Serialization` have a concept analogous to Java's [`serialVersionUID`](http://docs.oracle.com/javase/7/docs/api/java/io/Serializable.html)? cc/ @shanear

**Comment by shanear** [comment]
Rails serialization is pretty sparse, and we're doing something not recommended here, by saving an object in the session. Normally, we'd save it in the DB, and these problems would be handled by the Database Migration system in rails.

We'd need to hand-roll this mechanism.
