### ISSUE TITLE
Large values for form fields can trigger CookieOverflow (via saved forms)

### ISSUE THREAD

**Issue by orischwartz** [department-of-veterans-affairs/caseflow-certification#230]
It's possible to overflow the 4kb limit on cookie values because we're using `ActionDispatch::Session::CookieStore` for arbitrary user data in saved forms, 

We can

1. Skip saved form functionality if serialized form exceeds 4kb 
2. Use a different [session store](http://guides.rubyonrails.org/action_controller_overview.html#session)
3. Length-check all the fields, ensure that it's impossible to exceed 4kb...it may be that the user was trying enter a block of text that was too long to fit in form anyway.

Steps to reproduce:

1. Paste a large amount of text into the remarks field, 
2. Click certify

**Comment by shanear** [comment]
Did this actually happen to users? I assumed we'd never hit the 4kb limit.

**Comment by orischwartz** [comment]
It did, reported under the ominous subject: _"Caseflow not working?"_ It's easy to reproduce--paste a very large (but valid) block of text into remarks.

![ie9500](https://cloud.githubusercontent.com/assets/16327036/14089081/f5ed35fa-f500-11e5-8564-a9a46e6d7e46.png)

Logged as

```
ActionDispatch::Cookies::CookieOverflow (ActionDispatch::Cookies::CookieOverflow):
  vendor/bundle/ruby/2.2.0/gems/actionpack-4.2.5.2/lib/action_dispatch/middleware/cookies.rb:529:in `[]='
  vendor/bundle/ruby/2.2.0/gems/actionpack-4.2.5.2/lib/action_dispatch/middleware/session/cookie_store.rb:110:in `set_cookie'
  vendor/bundle/ruby/2.2.0/gems/rack-1.6.4/lib/rack/session/abstract/id.rb:351:in `commit_session'
  vendor/bundle/ruby/2.2.0/gems/rack-1.6.4/lib/rack/session/abstract/id.rb:226:in `context'
  vendor/bundle/ruby/2.2.0/gems/rack-1.6.4/lib/rack/session/abstract/id.rb:220:in `call'
  vendor/bundle/ruby/2.2.0/gems/actionpack-4.2.5.2/lib/action_dispatch/middleware/cookies.rb:560:in `call'
  vendor/bundle/ruby/2.2.0/gems/activerecord-4.2.5.2/lib/active_record/query_cache.rb:36:in `call'
  vendor/bundle/ruby/2.2.0/gems/activerecord-4.2.5.2/lib/active_record/connection_adapters/abstract/connection_pool.rb:653:in `call'
  vendor/bundle/ruby/2.2.0/gems/actionpack-4.2.5.2/lib/action_dispatch/middleware/callbacks.rb:29:in `block in call'
```

**Comment by shanear** [comment]
oof, yep thats the problem. hmm... not having a db sucks. lemme check out your fix.
