### ISSUE TITLE
Display remaining character count for text fields

### ISSUE THREAD

**Issue by orischwartz** [department-of-veterans-affairs/caseflow-certification#232]
As first described here https://github.com/department-of-veterans-affairs/caseflow-certification/pull/231#issuecomment-202576183

So user isn't surprised when we cut off their input

**Comment by shanear** [comment]
Is the only reason we're capping input fields is because of the cookie size restriction?
or is there another reason?

**Comment by orischwartz** [comment]
No, there's also a limit to the number of character we can fit in the form8 pdf. (We've thought about duplicating and appending as many page 2's as necessary to roll over every field but that's likely out of scope.)

It's actually possible to exceed the 4kb limit without maxing out all the fields.
