### ISSUE TITLE
Don't drop cookies if data is too large

### ISSUE THREAD

**Issue by paultag** [department-of-veterans-affairs/caseflow-certification#235]
The stupid 4K bug with Rails sessions is bad.

We need to back our session store with something better. Or use the cache (eww), or use multi-db (eww-er!).

However, us dropping this means users can't do the back and forth questions/view flow, they're stuck re-filling out the Form 8 every time.

**Comment by orischwartz** [comment]
Makes #233 obsolete if implemented

**Comment by orischwartz** [comment]
If we swap our session store to `CacheStore`, we can then swap it to `MemCacheStore`after deploying to cloud. `CacheStore` will work fine in current env because we only have 1 instance.

http://api.rubyonrails.org/classes/ActionDispatch/Session/CacheStore.html
