### ISSUE TITLE
Consider increasing the character limit for 6A, and 7A

### ISSUE THREAD

**Issue by shanear** [department-of-veterans-affairs/caseflow-certification#253]
They are only 140 characters right now. Seems very short.

We're getting feedback on this.

**Comment by KHarshawat** [comment]
Yep, this was when we had the cookie issue. Totally fine with increasing. Do we have a sense of how much people are filling in? 

The only UX concern here is if they go over the amount of space allotted in the F8 but I suspect we can just append a second second page with additional remarks.

**Comment by shanear** [comment]
@KHarshawat not really, no data :(

I'll bump it up to 1000 chars. Sound good?
