### ISSUE TITLE
Verify that Question 8C is working as intended

### ISSUE THREAD

**Issue by KHarshawat** [department-of-veterans-affairs/caseflow-certification#257]
We received this feedback via Chris:

> Item 8C on Form 8 did not ask if attorney was accredited

We should verify that question 8C is showing up as intended.

**Comment by KHarshawat** [comment]
FYI this is what the question is on the F8 

![image](https://cloud.githubusercontent.com/assets/6335546/14869173/aa62277e-0c86-11e6-8a03-f666581f7d1c.png)

**Comment by shanear** [comment]
This button only shows up if the user selects "Attorney" for 8A, which I think threw him off. Validated with Chris that this is working correctly.

Closing
