### ISSUE TITLE
Figure out how appeals should be certified with the National Work Queue

### ISSUE THREAD

**Issue by shanear** [department-of-veterans-affairs/caseflow-certification#274]
Right now, Caseflow requires that the certifying official be in the same RO as the appeal. With the introduction of National Work Queue, this is no longer the case.

How should we deal with this?

**Comment by KHarshawat** [comment]
As described in https://github.com/department-of-veterans-affairs/appeals-pm/issues/679 we do not need to restrict appeals by RO when we move to CSS so this issue will be OBE.

**Comment by KHarshawat** [comment]
Closing it now.
