### ISSUE TITLE
Users that switch between two different ROs are confused by unauthorized wording

### ISSUE THREAD

**Issue by orischwartz** [department-of-veterans-affairs/caseflow-certification#300]
Via NSD support ticket: 

> The customer is using VACOLS and is engaging case flow certification via vacols. When attempting to open the case the customer gets the alert that the case "unauthorized, appeal is not within your jurisdiction. However via Caseflow the case appears within the customers jurisdiction. 

Sanitized log output below
```
[yyyy@va.gov (RO27)] Started GET "/certifications/new/xxxx" for 127.0.0.1 at 2016-07-28 14:46:09 -0500
...
[yyyy@va.gov (RO27)] loaded VACOLS case xxxx:   0.010000   0.000000   0.010000 (  0.173162)
[yyyy@va.gov (RO27)] sent VBMS request VBMS::Requests::ListDocuments for zzzz   0.040000   0.030000   4.490000 (  4.898773)
[yyyy@va.gov (RO27)] Started GET "/unauthorized" for 127.0.0.1 at 2016-07-28 14:46:14 -0500
```

**Comment by orischwartz** [comment]
I will follow up with user but it looks like VACOLS has this specific case assigned to a different RO.

**Comment by orischwartz** [comment]
VACOLS lists RO70 (Louisville CLCW) for user is signed in as RO27 (Louisville). 

It's possible these two should be treated as the same ... will follow up with user and Jed if necessary.

**Comment by orischwartz** [comment]
User toggles between the two ROs. Easy fix is to add a prompt on the unauthorized page asking the user to sign in again if necessary. Something like:

> You are currently signed in as RO XXXX. Did you mean to sign in as a different RO for this case? 

And then either link to /logout or embed the login page again and have it overwrite their existing session.

**Comment by orischwartz** [comment]
Confirmed from user: 

>  I guess I didn’t understand what you meant by being signed in as RO27. ... you have no idea how relieved I am to figure out what I was doing wrong.

**Comment by orischwartz** [comment]
Boilerplate response for now: 

> You can sign into Caseflow Certification using ROXX, the same way you would sign into VACOLs as two different ROs.

> If you had signed in as ROYY for a different case, Caseflow will remember it and won’t prompt you to sign in again. So you’ll need to sign out first by clicking the “sign out” link from the dropdown menu in the top right (which shows your email address, see attached screenshot).

> After that, you’ll be prompted to sign in again. Sign in as ROXX. 

> Unfortunately you’ll have to do this each time you switch between the two ROs. In the future, we’ll make this easier to do by adding a link to the “unauthorized” page.

**Comment by KHarshawat** [comment]
This will probably become OBE when we move to CSS and stop restricting users by RO.
