### ISSUE TITLE
Migrate to Ruby-only Connect VBMS

### ISSUE THREAD

**Issue by shanear** [department-of-veterans-affairs/caseflow-certification#309]

**Comment by orischwartz** [comment]
Currently use the legacy hybrid Ruby/Java version of connect_vbms (which is [included in this repo](https://github.com/department-of-veterans-affairs/caseflow-certification/pull/86#issuecomment-191805468) under vendor/gems).

Switch to newer pure [Ruby implementation](https://github.com/department-of-veterans-affairs/connect_vbms/commits/cleanroom/no-java) after migrating our deployment to AWS.

cc @plusjeff

**Comment by KHarshawat** [comment]
@shanear to connect w/ @orischwartz on when to deploy. Should be careful not to overlap w/ bulk add users to CSS #544
