### ISSUE TITLE
Integrate with CSS

### ISSUE THREAD

**Issue by shanear** [department-of-veterans-affairs/caseflow-certification#310]
Current plan is to redirect to `cf.ds.va.gov`, and have that do the CSS SSO redirect. Thus we can strip all the Omniauth stuff out.

- [x] Add new certification domains to the DNS (NSD ticket created by @gmorgana-va)
- [x] Add permissions security checks
- [x] Modify the user class to work with the CSS user information instead of IAM.
- [x] Add rerouting code
- [x] Update ansible script with the environnment vars below (https://github.com/department-of-veterans-affairs/appeals-deployment/pull/108)
- [x] Add our application users to "Certify Appeal" function (tracked here: https://github.com/department-of-veterans-affairs/appeals-pm/issues/544)
- [x] Test in UAT

The final switch to CSS will be initiated through on the weekend of 9/26:
- [ ] Update the URL used in VACOLS

Environment variables needed
- `SSO_URL = "cf.ds.va.gov/auth/samlva"` omniauth url for SSO
- `SECRET_KEY_BASE` must match efolder express (this was confirmed)

**Comment by shanear** [comment]
@orischwartz we'll also need to request the following domains:

certification.cf.uat.ds.va.gov
certification.cf.preprod.ds.va.gov
certification.cf.ds.va.gov

Can you confirm that the IP's here are correct?
https://github.com/department-of-veterans-affairs/appeals-deployment/blob/master/docs/staging-NAT-mappings-NSOC.md
https://github.com/department-of-veterans-affairs/appeals-deployment/blob/master/docs/production-NAT-mappings-NSOC.md

**Comment by shanear** [comment]
After much frustration, I found out another caveat to sharing sessions in rails is that the `SECRET_KEY_BASE` must be the exact same. This will need to be accounted for in the ansibles.

**Comment by orischwartz** [comment]
Per discussion with @shanear today, instead of making `CSS_ENABLED` a manual switch, let's have application dynamically determine which SSO platform to use by inspecting the requested hostname. This way, deployment doesn't require coordination between VACOLS rollout and the application--we would only need to update the VACOLS URL.

**Comment by shanear** [comment]
Blocked on the DNS mapping...

**Comment by shanear** [comment]
Holding on Sentry and merging the two pulls mentioned above.

**Comment by orischwartz** [comment]
Deployed https://github.com/department-of-veterans-affairs/caseflow-certification/pull/315 to UAT  (using `-e app_version=css` git version hook) so we can test and hack via `etc/hosts`.

Only concerned about retaining backwards compatibility with SSOI/VACOLS login logic.

**Comment by orischwartz** [comment]
@shanear Next steps:

* Confirm CSS login in UAT by modifying local `/etc/hosts`

Then we can start tracking prod requirements.

**Comment by shanear** [comment]
@orischwartz the `certification.cf.*.va.gov` DNS entries are already in effect, so we shouldn't have to manipulate etc/hosts right?

**Comment by orischwartz** [comment]
Ah right. Yes, confirmed working in UAT (minus SSL errors for wrong domain).

**Comment by orischwartz** [comment]
@shanear Safe to close this in favor of the various (private) issues we're using to track rollout?

* Coordinate Rollout of CSS https://github.com/department-of-veterans-affairs/appeals-pm/issues/760
* Migrate Caseflow Certification Users to CSS https://github.com/department-of-veterans-affairs/appeals-pm/issues/643
* Determine How to Bulk Add Users in CSS to Migrate Certification to CSS https://github.com/department-of-veterans-affairs/appeals-pm/issues/544
