### ISSUE TITLE
Combine ROs where appropriate

### ISSUE THREAD

**Issue by shanear** [department-of-veterans-affairs/caseflow-certification#312]
Some ROs have two RO ids for the same location. There is often a need to certify cases for both of these ROs and it would be nice if the users didn't have to log in and log back out.

These are two tickets where the issue has come up:
https://github.com/department-of-veterans-affairs/caseflow-certification/issues/300
https://github.com/department-of-veterans-affairs/appeals-pm/issues/655

NOTE: If we start using CSS station IDs for determining RO, this will become an even bigger issue, because users won't be able to log in as another RO.

**Comment by KHarshawat** [comment]
Sent the following email to Chris:

> Hey Chris, our team is starting to migrate Caseflow Certification into a new sign in system. In order to do so we need to map the different Regional Offices to their respective VBMS Station IDs. We have most of them (see the attached document) but we’re missing the following. 
> 
> Can you help us find out what these RO station IDs are?
> 
> Best, Kavi

**Comment by shanear** [comment]
We need to figure out whether it's possible to have CSS users belong to multiple station ids. And if so, how does that work.

**Comment by KHarshawat** [comment]
@shanear here's the updated file with all station IDs except General Counsel, NCA, and VHA CO.

**Comment by KHarshawat** [comment]
Emailed the following to Michael and cc'd Shane

>Hi Michael, we had a question for you about CSS station Ids.
>
>Today our users access case files by logging in using a Regional Office number (e.g. RO31, RO17, etc). Some ROs have two RO ids for the same location and there is often a need to access case files for both of these ROs. If we start using CSS Station IDs for determining RO, this seems like it would cause a problem.
>
>Is it possible for CSS users to belong to multiple station IDs? If so, how would that work?

**Comment by KHarshawat** [comment]
Currently on hold until we can get an answer to the following: https://github.com/department-of-veterans-affairs/appeals-pm/issues/679

**Comment by KHarshawat** [comment]
Re: department-of-veterans-affairs/appeals-pm#679 we don't have to restrict appeals based on user's RO. Removing on hold label and moving this to the current sprint column until Shane is back.

**Comment by shanear** [comment]
This is no longer necessary, because we're removing the RO access check:

https://github.com/department-of-veterans-affairs/caseflow-certification/issues/317
