### ISSUE TITLE
Begin recording timestamps for certifications

### ISSUE THREAD

**Issue by shanear** [department-of-veterans-affairs/caseflow-certification#320]
A certification record should be created locally the first time it's viewed. To start, this record will be used to track timestamps for events on the certification:

- started_at (created_at)
- nod_matching_at
- form9_matching_at
- soc_matching_at
- ssocs_matching_at
- documents_matching_at
- completed_at

**Comment by shanear** [comment]
@cmgiven this list look good to you? Think it's ok to group all ssocs matching into one timestamp. It simplifies things a lot.

**Comment by cmgiven** [comment]
Looks good. One question: how would we know when an SSOC is not expected? Want to be able to remove certifications that do not need an SSOC from both numerator and denominator there.

**Comment by shanear** [comment]
@cmgiven We could say that they "match" immediately, since (no ssocs == no ssocs)

**Comment by KHarshawat** [comment]
Note from standup: Dependent on Postgres and changes in architecture. Was dependent on Sentry for Certification which  is done.

**Comment by shanear** [comment]
@cmgiven So after mulling over this for a little while, I'm having a hard time deciding where to account for some of our events. The line between where we record data is still pretty fuzzy. Here's an example:

There is  a very unlikely scenario where a user tries to start a certification that doesn't have the proper data in VACOLS. I believe the VACOLS UI prevents this, but I'd be nice to know when if it ever occurs.

1) Sentry - There is the case to be made that this is actually an exceptional event and should just be recorded as an error. However, I feel like a sentry error implies that it's a bug, and thus it's something we should fix. This situation is not something we'd "fix", it's more like a 404. There's no way we can prevent a user from entering an invalid appeal id into the url bar.

2) The App Dashboard - This is nice because we have complete control over how to record and query for this event. However, it's annoying to have an entire column and section of our dashboard dedicated to an edge case like this. 

3) Google Analytics - Since this is sort of a page view, it makes sense that we'd record it. But I'm noticing that no one ever looks at Google Analytics, and sometimes rare events get buried underneath all the noise. I tried to check out what our GA looked like right now, and they display just so much data that isn't really easy to parse or understand. It's also annoying and unintuitive to have such similar data in two places (mismatched document times are in the dashboard, missing VACOLS data events in GA).

**Summary**: 
- Do we want to capture specific view events in GA? or keep everything in the App Dashboard?
- If we're just using GA for URL hits, is that at all valuable?
- What's the best way to use GA? 

Thoughts?

**Comment by cmgiven** [comment]
Let's rule out the dashboard: it doesn't have much ongoing value. It could be tracked in the database and reported on periodically, but I agree with your view re: awkwardness.

One way to consider whether to use Sentry or GA for this would be severity. I'm assuming we don't track 404s in Sentry. My sense is this is not something that we need to be proactive in identifying: if somehow VACOLS is sending unready appeals to certification, we'd hear about it from users pretty quickly. If someone has just manually edited a URL, they know what they did. Kinda like 404s, where they can indicate that we screwed up, but more often than not it's just noise. But if this was a thing that should never happen, that wasn't so trivial for a user to accidentally trigger, Sentry would probably make sense.

I assume this page already returns a 400-series status? In which case, perhaps GA's already tracking it?

**Comment by shanear** [comment]
Well, I've started down the route of having everything tracked in the certification DB. The benefit of a dashboard is that we can optimize it to show what we want to see, how we want to see it.

Yes, GA is already tracking it, but like I said, no one really looks at GA, or knows which of the 100's of GA screens to look at, or knows to click to page 2 to see the small number hits to this URL, or know that those hits represent an issue.

**Comment by shanear** [comment]
Alright, after some refactoring and adding in of Postgres, I have a Certification model

**Comment by cmgiven** [comment]
What are the options for first preview timestamp? Seems like it would be useful, as if something was previewed but not submitted, it could indicate that our generated Form 8 was deemed inaccurate for some reason.

**Comment by shanear** [comment]
@cmgiven we can record the time when a certification is first previewed. The big thing that would give us is the amount of time between preview and confirmation. We still wouldn't be able to know how many times they go back and forth and make edits.

**Comment by cmgiven** [comment]
At least for me, I'm not seeing an issue there. If we are interested in that, GA is going to be a better choice; we don't want to reimplement all of analytics.

**Comment by shanear** [comment]
Config PR: https://github.com/department-of-veterans-affairs/appeals-deployment/pull/129

**Comment by shanear** [comment]
@orischwartz alright the correctly configured RDS instance is up. The current config in appeals-deployment should work. The database `caseflow_certification` is also live.

Checked it with psql.

**Comment by shanear** [comment]
Deployed this morning to prod
