### ISSUE TITLE
Remove IAM logic

### ISSUE THREAD

**Issue by shanear** [department-of-veterans-affairs/caseflow-certification#325]
- [ ] Merge `paultag/css` branch of Omniauth-saml-va into master (https://github.com/department-of-veterans-affairs/omniauth-saml-va/tree/paultag/css). Update Gemfiles in 
  - [ ] eFolder Express 
  - [ ] Caseflow Certification 
- [ ] Remove `DEPLOY_ENV` from certification in appeals deployment
- [ ] Change certification to use `COOKIE_DOMAIN` instead of `:all` for sessions
- [ ] Strip IAM related User logic and controller actions in certification repo

**Comment by shanear** [comment]
@orischwartz this look good to you?

**Comment by orischwartz** [comment]
LGTM :+1:
