### ISSUE TITLE
Provide a History of cases for which an EP has been created

### ISSUE THREAD

**Issue by lakohl** [department-of-veterans-affairs/caseflow-certification#360]
Allow employees to keep track of which cases they have worked and when.

**Comment by KHarshawat** [comment]
@lakohl is this a dupe of a story we created last sprint? If so could you please mark as such and close?

**Comment by KHarshawat** [comment]
@lakohl can you please add appropriate mocks here?

**Comment by KHarshawat** [comment]
Dupe of https://github.com/department-of-veterans-affairs/caseflow-certification/issues/386
