### ISSUE TITLE
Create Designs for EP Dispatch

### ISSUE THREAD

**Issue by lakohl** [department-of-veterans-affairs/caseflow-certification#371]
Create designs for each stage of EP creation.

**Comment by lakohl** [comment]
@abbyraskin here are some initial sketches. The Caseworker view starts with two versions of the same page.
[Manager Landing View.pdf](https://github.com/department-of-veterans-affairs/caseflow-certification/files/557123/Manager.Landing.View.pdf)
[Caseworker View.pdf](https://github.com/department-of-veterans-affairs/caseflow-certification/files/557124/Caseworker.View.pdf)

**Comment by abbyraskin** [comment]
One note for our team is that I'm not sure "Create End Product" will resonate with users as much as "Establish Claim" or "New Claim" (this is the language they use from VBMS + the internal shorthand "CEST"ing). The EP is simply one part of this form submission workflow.

**Comment by KHarshawat** [comment]
@abbyraskin great point. I'm creating an issue to review all the designs with you Lara and myself to make sure we're incorporating all of the things you've learned from conducting research.  Would you mind scheduling?

**Comment by KHarshawat** [comment]
@lakohl can we close this issue now that the other issues have been created?

**Comment by lakohl** [comment]
First draft of design has been created and coded. Closing this issue.

**Comment by abbyraskin** [comment]
(will schedule first thing this AM when I have access to your calendars again!)
