### ISSUE TITLE
Caseworker Landing: History

### ISSUE THREAD

**Issue by lakohl** [department-of-veterans-affairs/caseflow-certification#389]
As a caseworker, when I visit the landing page, I can see a list of the cases I processed with the most recently processed case at the top.

Possible Values for Results: EP Completed, Routed to RO, Cancelled

<img width="693" alt="screen shot 2016-10-27 at 4 10 56 pm" src="https://cloud.githubusercontent.com/assets/4975959/19783981/02400784-9c62-11e6-8c9f-4a67272f7857.png">

**Comment by joofsh** [comment]
Completed by https://github.com/department-of-veterans-affairs/caseflow-certification/pull/427
