### ISSUE TITLE
Better handling of IAM handoff than caseflow classic

### ISSUE THREAD

**Issue by paultag** [department-of-veterans-affairs/caseflow-certification#47]
Ported from:

https://github.com/department-of-veterans-affairs/caseflow/issues/577#issuecomment-189645894

Basically, in the handoff, both Caseflow and IAM forget what case is being worked on.

I've just changed the 404 page in caseflow classic to suggest reloading from VACOLS, but I don't think that's the best solution. I think we should spend some time making this bullet proof on this rewrite

**Comment by paultag** [comment]
I think this is done? cc @orischwartz

**Comment by shanear** [comment]
Yeah, theres an automated test for it and everything.
