### ISSUE TITLE
Clean up help page

### ISSUE THREAD

**Issue by paultag** [department-of-veterans-affairs/caseflow-certification#53]
There are a lot of little issues on the help page. 

- Arrows don't render correctly on some screenshots
- Some screenshots need to look prettier
- Some screenshots ought to be cropped
- The fake Appellant ID should be blurred out or pixelated
- There should be more links at the top of the page

# Comments

## Kavi

Draft of new help content

**What is Caseflow Certification?**

Caseflow Certification, a web-based tool that makes it easy to automatically fill out an electronic Form 8 for paperless appeals. The tool was built by the United States Digital Service at the Department of Veterans Affairs in close collaboration with Decision Review Officers in regional offices all over the country.

**What does Caseflow Certification do?**

Caseflow eliminates the need to fill out a PDF Form 8 for appeals. It automatically checks to make sure documents such as the Form 9, Notice of Disagreement (NOD), Statement of Case (SOC), and Supplemental Statements of Case (SSOC) have been added to an appeal. It also verifies that these documents are consistent between VBMS and VACOLS. Once verified, the tool lets you fill out an electronic Form 8. It automatically pre-fills some of the Form 8 data from VACOLS and VBMS. It will then generate a PDF of the Form 8 and allow you to easily upload that document to the VBMS eFolder. 

You should use Caseflow with paperless appeals that are ready to be certified. 

**How do I launch Caseflow Certification?**

Once you're ready to certify an appeal, open and log in to VACOLS then search for the Appeal ID. Once the date for the Form 9, NOD, SOC< and (optionally) SSOC have been entered into VACOLS, click the Certify Appeal button from the process menu. You can also select this option from the search results window (show example) or the update appeal window (show example).

When you click the certify button, you'll see a new window pop up. Since this is a paperless appeal, we'll select VBMS eFolder.  Next, you'll see a notification in VACOLS and a new window will open up launching Caseflow.

**How do I log in to Caseflow Certification?**

If it's the first time you're using Caseflow Certification in a while you'll be asked to log in twice. The first time you'll want to log using your standard VA credentials (or PIV if you like). On the second login page, you'll need to log in using your regional office VACOLS credentials.

**Why does Caseflow say it cannot find documents in VBMS?**

Once you're logged in, Caseflow will check to see if documents in the VBMS eFolder (such as the NOD, SOC, and Form 9) match the dates entered in VACOLS.  Caseflow will tell you it cannot find documents in VBMS if it cannot detect these documents. 

**What are the reasons Caseflow may not be able to find documents in VBMS?**

There are usually three reasons Caseflow wouldn't be able to find a document: 

1. The dates of the document in question are inconsistent between VACOLS and VBMS.
 - If the dates are inconsistent you can change the date in either VACOLS or VBMS to match the other then click the `refresh` button in Caseflow. 
2. The label of the document in question is missing or incorrect in VBMS
 - If a document uses a different label (such as "Correspondence - Miscellaneous") or missing, add the more descriptive label to the document in the VBMS document settings and click the `refresh` button in Caseflow. 
3. The document in question has not been uploaded to VBMS.
 - If a document is missing from the eFolder, the appeal is not ready to be certified and you should click the `Cancel Certification` button.

**What should I do if an eFolder document contains multiple types of information?**

Occasionally, especially with older appeals, an NOD or a Form 9 will be included in a document with a more general label such as a Statement in Support of Claim. These documents could contain other information such as testimony or evidence. The short-term guidance for this situation is to duplicate the document by saving it to your computer, then re-uploading it to the eFolder. Add the appeal-specific label (NOD, Form 9, SOC, or SSOC) to the newly uploaded document and make sure the date matches the one listed in VACOLS.

VBMS is pursuing a long term solution to add multiple labels to a document to avoid the need to duplicate documents.

**How do I fill out an electronic Form 8?**

Once all the documents are detected, you'll see a web form that lets you fill out all the details to complete a Form 8. Required questions are marked by a red asterisk.

To make things go a little faster, some of the fields are automatically pre-filled using data from VBMS and VACOLS. If something is pre-filled but doesn't look right, you can always manually correct the data on this page.

You'll also notice that some questions are only shown if relevant. For example, question 10b, "Is the hearing transcript in file?" only shows up if you indicate that a hearing was held. 

Once you've finished filling out all the relevant details on this page, click the `Preview Completed Form 8` button.

**What is the Preview Form 8 page?**

This page allows you to preview the completed Form 8. If anything looks wrong you can click the `Go back and make edits` button to fix the problem on the previous page. If, after review, the Form 8 looks correct, click the `Upload and Certify` button. 

**What happens when I click the `Upload and Certify` button?**

The Form 8 will automatically be uploaded to the eFolder, a certification date will be added to the appeal, and the appeal will be certified to the Board of Veterans Appeals!

Once you see the "Congratulations" page you can close the browser window and open up another appeal using VACOLS.

**What if I encounter a problem that prevents me from certifying the appeal?**

If you are unable to certify the appeal using Caseflow Certification, you can click the `Cancel Certification` link. You'll see a confirmation indicating the certification has been cancelled and you can close the window. 

It's important to know that you cannot `Cancel Certification` after clicking the `Upload and Certify` button because the Form 8 will have already been added to the eFolder and cannot be deleted.

**What do I do if I need help?**

If you need help remembering how to use Caseflow Certification and want to get back to these instructions, you can click your email address in the top right corner of the application and select the `Help` option.

**How do I certify paper appeals?**

You can only certify paperless appeals with Caseflow Certification. If you have a paper appeal, you'll have to manually fill out a Form 8. Once it's completed, find the appeal in VACOLS, click the "Certify" button, then select the "Hardcopy claims folder or Virtual VA" option. From here you'll need to manually fill out a Form 8 for the appeal and type in the Certification Date this window. 

**What if my appeal has the Form 9, NOD, SOC, and/or SSOC in Virtual VA?**

Caseflow Certification does not work with appeals where the Form 9, NOD, SOC, or SSOC are stored in Virtual VA. If, in the rare case, you have an appeal that has these specific documents in a Virtual VA, you'll have to manually fill out and upload a regular Form 8 and manually enter the Certification Date in VACOLS. Once the Form 8 is completed, open the appeal in VACOLS, click the Certify button, and select the "Hardcopy claims folder or Virtual VA" option. 

## more Kavi

Tracking additional questions we've been asked during the pilot:

Will we not be able to use this process on cases where a 646 is needed, as we cannot put a CERT date in VACOLS until the 646 is completed by the POA.  We usually complete the CERT package to include form 8, certification worksheet, and request for 646 (if the POA is located in our building) when we are certifying a case, but we cannot update the CERT date in VACOLS until the 646 is of record, unless the veteran has requested a travel board hearing.
 
**Kavi's response:** You are correct, you cannot use Caseflow to certify appeals where a 646 has not yet been completed by a POA as Caseflow sets the certification date and uploads the Form 8 at the same time. In this situation, you would have to wait for the 646 to be completed before certifying the appeal.

We are also wondering what the process will be on cases where more than one form 9 record have been merged together, in those instances the dates in VACOLS may not match the dates in VBMS, as there are multiple appeals merged in one VACOLS record, and the oldest appeal information is what VACOLS will show.  Additionally sometimes the veteran will submit several different NODs or form 9s as duplicates, will this cause a problem for case flow when it is trying to locate the records in VBMS?

**Kavi's response:** Caseflow works off of the date entered in VACOLS. When an appeal is merged, VACOLS uses the oldest appeals document dates (NOD, SOC, Form 9 dates). So if there were multiple Form 9s, Caseflow would look for the oldest Form 9 for the appeal, just as BVA does today.

## SO MUCH KAVI 

We should make sure language is consistent with training videos script:

https://github.com/department-of-veterans-affairs/appeals-pm/blob/master/administration/certification/training_script.md

**Comment by paultag** [comment]
More at https://github.com/department-of-veterans-affairs/caseflow/issues/547

**Comment by paultag** [comment]
This depends on #55 - too -- @KHarshawat are you happy with the stuff above?

**Comment by KHarshawat** [comment]
@paultag planning on giving you finalized content for this tomorrow morning. Sorry I couldn't get to it tonight.

**Comment by KHarshawat** [comment]
@paultag Here's the updated help page content. Still collecting screenshots:

[Caseflow Certification Help Page 20160303.docx](https://github.com/department-of-veterans-affairs/caseflow-certification/files/156851/Caseflow.Certification.Help.Page.20160303.docx)

**Comment by paultag** [comment]
@KHarshawat Awesome, keep posting away, but I'm going to take the bug to start work on this.

**Comment by paultag** [comment]
@KHarshawat Sent a PR in with that document content - still need screenshots and stuff. Re-assigning to you, but i think we also need some @gmorgana-va with the bug #55
