### ISSUE TITLE
Update Missing Documents Instructions

### ISSUE THREAD

**Issue by paultag** [department-of-veterans-affairs/caseflow-certification#55]
Update text on 'Find missing documents' page to include specific labels that are required to be used.

https://github.com/department-of-veterans-affairs/caseflow/issues/606

**Comment by paultag** [comment]
@gmorgana-va I'm gonna assign this to you - we need verbage to throw onto the page.

**Comment by paultag** [comment]
@gmorgana-va I sent in a PR for the help page featuring text @KHarshawat wrote up at #89 - we should likely add it there -- unless you'd like a page just for document updating somehow.

**Comment by gmorgana-va** [comment]
@KHarshawat @paultag, summarizing our conversation: hyperlink the "labeled correctly" text and point it to the appropriate FAQ/help content

**Comment by paultag** [comment]
@gmorgana-va wait, what's the actual text to instruct them on what to do? Was that in Kavi's thing?

**Comment by gmorgana-va** [comment]
Hyperlink to this section of the help page: 

https://github.com/department-of-veterans-affairs/caseflow-certification/blob/34557abf1ede33f9546abf38d7892ba81b1ed66a/app/views/help/show.html.erb#L91

**Comment by paultag** [comment]
PR up in https://github.com/department-of-veterans-affairs/caseflow-certification/pull/98
