### ISSUE TITLE
Determine Form 8 clean up policy

### ISSUE THREAD

**Issue by paultag** [department-of-veterans-affairs/caseflow-certification#56]
https://github.com/department-of-veterans-affairs/caseflow/issues/10

**Comment by orischwartz** [comment]
* Delete Form 8 PDF after uploading to efolder.
* Delete any Form 8 PDF that is > 24 hours old
    - Same process, e.g., [`TimerTask`](http://www.rubydoc.info/github/ruby-concurrency/concurrent-ruby/Concurrent/TimerTask) (initiate on Rails startup, destroy on shutdown)
    - Separate process, e.g, `ActiveJob`

**Comment by shanear** [comment]
dealing with this here:
https://github.com/department-of-veterans-affairs/deployment/issues/227
