### ISSUE TITLE
Add Monitoring to Caseflow

### ISSUE THREAD

**Issue by paultag** [department-of-veterans-affairs/caseflow-certification#57]
https://github.com/department-of-veterans-affairs/caseflow/issues/22

**Comment by KHarshawat** [comment]
Listing out the things that I'd like to monitor (will create a separate GH issue for each if needed):

- [ ] VBMS connection (up/down/slow/etc)
- [ ] VACOLS connection (up/down/slow/etc)
- [ ] What fields are being edited? 
- [ ] How far are people getting along in the process? Error/Form 8/Preview/Success (see YuleLog)
- [ ] Error pages (508, 404, etc)
- [ ] Log BFKEY so we can investigate further
- [ ] Log Employee ID so we can reach out for investigation

**Comment by orischwartz** [comment]
We'll log everything in application logs for now. We can also use Google Analytics events to track all of our business metrics:

* How far are people getting along in the process? Error/Form 8/Preview/Success

Currently blocked on Analytics account access

**Comment by KHarshawat** [comment]
@shanear can you make sure we'll be logging everything here we ought to be in Sentry?

**Comment by KHarshawat** [comment]
We have a sentry server up and running. Just need to add the project and add the proper configurations to Caseflow Certification.

 (see this issue: https://github.com/department-of-veterans-affairs/caseflow-certification/issues/308)

**Comment by shanear** [comment]
With all the changes we're making to Certification I think it's really important that we keep a close eye on the application errors. For that reason, I'm going to tackle configuring Sentry for Certification first, and pull this into the current sprint.

@KHarshawat @orischwartz

**Comment by shanear** [comment]
Closing this issue once we've connected it to sentry. Adding tickets for other unresolved monitoring tasks.

**Comment by shanear** [comment]
Going to deploy and test the integration after the following are merged:

https://github.com/department-of-veterans-affairs/appeals-deployment/pull/121
https://github.com/department-of-veterans-affairs/caseflow-certification/pull/323

**Comment by shanear** [comment]
@orischwartz I think we should prioritize this over the CSS stuff. Since it will be valuable to have when we deploy the CSS stuff (to see if there are any errors).

**Comment by shanear** [comment]
Tested it! Sentry is live in certification.
