### ISSUE TITLE
Add Unicode support to the PDF Filling out code

### ISSUE THREAD

**Issue by paultag** [department-of-veterans-affairs/caseflow-certification#60]
https://github.com/department-of-veterans-affairs/caseflow/issues/291

**Comment by orischwartz** [comment]
A bigger concern is pasting Windows-1252 encoded text (**7A** below):

![pdf char encoding](https://cloud.githubusercontent.com/assets/16327036/13649006/88e4febc-e609-11e5-87b7-fc1e016318c9.png)
