### ISSUE TITLE
Add the word required to required questions.

### ISSUE THREAD

**Issue by KHarshawat** [department-of-veterans-affairs/caseflow-certification#87]
We currently only use a red-asterisck to indicate required questions. Users don't often notice it. We should figure out a way to make these more obvious.

**Comment by KHarshawat** [comment]
![image](https://cloud.githubusercontent.com/assets/6335546/13495250/9d8c77d8-e117-11e5-853d-44216cb01655.png)

![image](https://cloud.githubusercontent.com/assets/6335546/13495259/aeeb5c06-e117-11e5-80c5-66861b705b61.png)

![image](https://cloud.githubusercontent.com/assets/6335546/13495276/c4a5b4c4-e117-11e5-85c0-a56526922743.png)

**Comment by orischwartz** [comment]
This is easy to do on text inputs (just add `<span class="usa-additional_text">Required</span>`) in the `label` but the [style guide](https://playbook.cio.gov/designstandards/form-templates/) is unclear how to handle radio inputs. We could add a margin-left when in a `legend`.

**Comment by shanear** [comment]
Added an issue in the USWDS:
https://github.com/18F/web-design-standards/issues/1082

in the meantime, I'll show Kavi some options and we can go with one of those.

**Comment by shanear** [comment]
@KHarshawat 

## Option 1:
put required underneath the question:
<img width="490" alt="screenshot 2016-03-25 13 26 30" src="https://cloud.githubusercontent.com/assets/1596259/14049772/bc93b04c-f28d-11e5-875a-592304e13d0c.png">

<img width="532" alt="screenshot 2016-03-25 13 32 31" src="https://cloud.githubusercontent.com/assets/1596259/14049822/1bdcbf4e-f28e-11e5-840e-4ec92eb6da06.png">

## Option 2
right align it (showing an example with a long question)

<img width="489" alt="screenshot 2016-03-25 13 29 44" src="https://cloud.githubusercontent.com/assets/1596259/14049847/3bab4480-f28e-11e5-8632-7595988505c3.png">

<img width="519" alt="screenshot 2016-03-25 13 29 34" src="https://cloud.githubusercontent.com/assets/1596259/14049851/451c502c-f28e-11e5-8502-6082738ad36b.png">

## Option 3
go back to the drawing board :smile:

**Comment by KHarshawat** [comment]
@shanear How about this:

![image](https://cloud.githubusercontent.com/assets/6335546/14085451/ec0916e8-f4ed-11e5-8f8f-04d4afc8e808.png)

![image](https://cloud.githubusercontent.com/assets/6335546/14085454/f2f7ec36-f4ed-11e5-8945-5cff88ddf7ec.png)

**Comment by shanear** [comment]
@KHarshawat well, that would be a departure from the USWDS, and a big motivation for this story was to be on the same page as the USWDS. We want to do that?

If we do, would we want to make the required marks on text fields in red like that too?

**Comment by KHarshawat** [comment]
@shanear Given that USWDS doesn't support this right now and we don't know when they will I suggest we do this for the time being, then send our implementation back to USDWS as a proposal for how they might implement this more broadly. If they come up with a final design that meets our needs but is different than this approach in a few months, I think we can remove our customization and use theirs. 

I think we should use this consistently with Required text fields and radio buttons.

**Comment by shanear** [comment]
@KHarshawat sounds good

**Comment by KHarshawat** [comment]
@shanear I added a comment in the USWDS issue you mentioned above.
