### ISSUE TITLE
Add some contents to the what's new page so it's not blank

### ISSUE THREAD

**Issue by orischwartz** [department-of-veterans-affairs/caseflow-certification#91]
Maybe an introductory announcement, borrow content from @KHarshawat 's announcement letter?

**Comment by KHarshawat** [comment]
Welcome to Caseflow Certification! 

As many of you know, our organization is facing an unprecedented rise in benefit claims appeals with appeals rising by more than a third over the last three years. The appeals process is cumbersome for veterans and VA employees alike. Our team has turned it's attention toward improving the tools you use everyday to process these appeals.

For the last several months, the Digital Service has been working closely with Decision Review Officers, Veteran Service Representatives, and other employees in regional offices all over the country to develop a new tool called Caseflow Certification. This tool is a web-based application that integrates with tools you already use, VBMS and VACOLS, and allows you to automatically fill out an electronic Form 8 for paperless appeals.

If we can process appeals faster and more reliably and serve our veterans more efficiently. By focusing on your needs, our team has started the task this burdensome and manual process automated and simple. We'll continue to update the tool with new features and improvements in response to your feedback. 

On behalf of the Digital Service thank you for your continued service to the VA and America's Veterans.

- Kavi Harshawat on behalf of the United States Digital Service at the VA
